name: foodmarcos
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.1
  image_picker: ^1.1.2
  tflite_flutter: ^0.11.0

  path_provider: ^2.0.15
  sqflite: ^2.4.1
  image: ^4.5.4
  fl_chart: ^1.0.0
  provider: ^6.1.5
  path: ^1.9.1
  permission_handler: ^12.0.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/food_classifier.tflite
    - assets/class_names.txt
